services:
  options_monitor:
    build:
      context: https://github.com/jwplatta/options-monitor.git#main
    profiles: [dev]
    env_file:
      - envs/${ENV}.env
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_BUCKET: tickrake-intraday
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      S3_BUCKET: tickrake
    volumes:
      - ~/.tickrake:/root/.tickrake:ro
      - ~/.aws:/root/.aws:ro
    depends_on:
      - minio
    restart: unless-stopped
