universes:
  spx_symbols:
    - symbol: $SPX
      option_roots: [SPXW]

  0dte_symbols:
    - symbol: $SPX
      option_roots: [SPXW]
    - symbol: $NDX
      option_roots: [NDXP]
    - symbol: SPY
    - symbol: QQQ
    - symbol: IWM
