- symbol: ADBE
- symbol: ACN
- symbol: ADSK
- symbol: ADP
- symbol: CDNS
- symbol: CRM
- symbol: DAY
- symbol: EPAM
- symbol: FICO
- symbol: GEN
- symbol: GPN
- symbol: INTU
- symbol: IT
- symbol: MA
- symbol: MSCI
- symbol: NTAP
- symbol: NOW
- symbol: ORCL
- symbol: PAYC
- symbol: PAYX
- symbol: PYPL
- symbol: SNPS
- symbol: V
- symbol: AAPL
- symbol: ANET
- symbol: CSCO
- symbol: DELL
- symbol: HPQ
- symbol: HPE
- symbol: STX
- symbol: WDC
- symbol: AMD
- symbol: AMAT
- symbol: AVGO
- symbol: INTC
- symbol: KLAC
- symbol: LRCX
- symbol: MCHP
- symbol: MPWR
- symbol: MU
- symbol: NVDA
- symbol: 'ON'
- symbol: QCOM
- symbol: SWKS
- symbol: TER
- symbol: TXN
- symbol: IBM
- symbol: DXC
- symbol: MSFT
- symbol: MRVL
- symbol: TSLA
- symbol: FTNT
- symbol: ADI
- symbol: NXPI
- symbol: CRWD
- symbol: PANW
- symbol: NFLX
- symbol: PLTR
- symbol: META
- symbol: GOOGL
- symbol: GOOG
- symbol: AMZN
- symbol: UBER
- symbol: HOOD
- symbol: SCHW
- symbol: SBUX
- symbol: SPCX
- symbol: SMCI
- symbol: CRWV

