services:
  spx_short_options:
    build:
      context: https://github.com/jwplatta/tickrake.git#main
    image: tickrake:latest
    env_file:
      - ../env/secrets.env
      - ../env/dev.env
    environment:
      TICKRAKE_JOB_FILE: /root/jobs/spx_short_options.rb
    volumes:
      - ~/.tickrake-dev:/root/.tickrake-dev
      - ~/.schwab_rb:/root/.schwab_rb
      - ~/.aws:/root/.aws:ro
      - ../jobs:/root/jobs:ro
    restart: unless-stopped

  spx_long_options:
    image: tickrake:latest
    env_file:
      - ../env/secrets.env
      - ../env/dev.env
    environment:
      TICKRAKE_JOB_FILE: /root/jobs/spx_long_options.rb
    volumes:
      - ~/.tickrake-dev:/root/.tickrake-dev
      - ~/.schwab_rb:/root/.schwab_rb
      - ~/.aws:/root/.aws:ro
      - ../jobs:/root/jobs:ro
    restart: unless-stopped

  es_futures_quotes:
    image: tickrake:latest
    env_file:
      - ../env/secrets.env
      - ../env/dev.env
    environment:
      TICKRAKE_JOB_FILE: /root/jobs/es_futures_quotes.rb
    volumes:
      - ~/.tickrake-dev:/root/.tickrake-dev
      - ~/.schwab_rb:/root/.schwab_rb
      - ~/.aws:/root/.aws:ro
      - ../jobs:/root/jobs:ro
    restart: unless-stopped

  compact_spxw:
    image: tickrake:latest
    env_file:
      - ../env/secrets.env
      - ../env/dev.env
    environment:
      TICKRAKE_JOB_FILE: /root/jobs/compact_spxw.rb
    volumes:
      - ~/.tickrake-dev:/root/.tickrake-dev
      - ~/.schwab_rb:/root/.schwab_rb
      - ~/.aws:/root/.aws:ro
      - ../jobs:/root/jobs:ro
    restart: unless-stopped
