services:
  stock_options:
    build:
      context: https://github.com/jwplatta/tickrake.git#main
    image: tickrake:latest
    env_file:
      - ../env/secrets.env
      - ../env/prod.env
    environment:
      TICKRAKE_JOB_FILE: /jobs/stock_options.rb
    volumes:
      - ~/repos/quant-infra/jobs:/jobs:ro
      - ~/.tickrake:/root/.tickrake
      - ~/.schwab_rb:/root/.schwab_rb
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped

  etf_options:
    image: tickrake:latest
    env_file:
      - ../env/secrets.env
      - ../env/prod.env
    environment:
      TICKRAKE_JOB_FILE: /jobs/etf_options.rb
    volumes:
      - ~/repos/quant-infra/jobs:/jobs:ro
      - ~/.tickrake:/root/.tickrake
      - ~/.schwab_rb:/root/.schwab_rb
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped

  spx_0dte_options:
    image: tickrake:latest
    env_file:
      - ../env/secrets.env
      - ../env/prod.env
    environment:
      TICKRAKE_JOB_FILE: /jobs/spx_0dte_options.rb
    volumes:
      - ~/repos/quant-infra/jobs:/jobs:ro
      - ~/.tickrake:/root/.tickrake
      - ~/.schwab_rb:/root/.schwab_rb
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped

  spx_short_dated_options:
    image: tickrake:latest
    env_file:
      - ../env/secrets.env
      - ../env/prod.env
    environment:
      TICKRAKE_JOB_FILE: /jobs/spx_short_dated_options.rb
    volumes:
      - ~/repos/quant-infra/jobs:/jobs:ro
      - ~/.tickrake:/root/.tickrake
      - ~/.schwab_rb:/root/.schwab_rb
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped

  spx_longer_dated_options:
    image: tickrake:latest
    env_file:
      - ../env/secrets.env
      - ../env/prod.env
    environment:
      TICKRAKE_JOB_FILE: /jobs/spx_longer_dated_options.rb
    volumes:
      - ~/repos/quant-infra/jobs:/jobs:ro
      - ~/.tickrake:/root/.tickrake
      - ~/.schwab_rb:/root/.schwab_rb
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped

  futures_candles:
    image: tickrake:latest
    env_file:
      - ../env/secrets.env
      - ../env/prod.env
    environment:
      TICKRAKE_JOB_FILE: /jobs/futures_candles.rb
    volumes:
      - ~/repos/quant-infra/jobs:/jobs:ro
      - ~/.tickrake:/root/.tickrake
      - ~/.schwab_rb:/root/.schwab_rb
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped

  compact_spxw:
    image: tickrake:latest
    env_file:
      - ../env/secrets.env
      - ../env/prod.env
    environment:
      TICKRAKE_JOB_FILE: /jobs/compact_spxw.rb
    volumes:
      - ~/repos/quant-infra/jobs:/jobs:ro
      - ~/.tickrake:/root/.tickrake
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped

  compact_non_spxw_option_samples:
    image: tickrake:latest
    env_file:
      - ../env/secrets.env
      - ../env/prod.env
    environment:
      TICKRAKE_JOB_FILE: /jobs/compact_non_spxw_option_samples.rb
    volumes:
      - ~/repos/quant-infra/jobs:/jobs:ro
      - ~/.tickrake:/root/.tickrake
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped
