services:
  spx_short_options:
    build:
      context: https://github.com/jwplatta/tickrake.git#main
    image: tickrake:latest
    env_file:
      - ../env/secrets.env
      - ../env/dev.env
    environment:
      TICKRAKE_JOB: spx_short_options
    volumes:
      - ~/.tickrake-dev:/root/.tickrake-dev
      - ~/.schwab_rb:/root/.schwab_rb:ro
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped

  spx_long_options:
    image: tickrake:latest
    env_file:
      - ../env/secrets.env
      - ../env/dev.env
    environment:
      TICKRAKE_JOB: spx_long_options
    volumes:
      - ~/.tickrake-dev:/root/.tickrake-dev
      - ~/.schwab_rb:/root/.schwab_rb:ro
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped
